### ISSUE TITLE
How to use in .net project

### ISSUE THREAD

**Issue by damien122** [3F/7z.Libs#2]
Hi @3F

Thanks for the project and the support 👍 
Could you please help me to include this dll into my .net project on Mac?
Every time when I try to include the dll as reference I got this error message:

![image](https://user-images.githubusercontent.com/7516098/198975636-e54b39f2-7e80-4f01-bc8a-1e8dc7d11476.png)

**Comment by 3F** [comment]
Hello,

The error because, yes,
you're trying to use native modules without dotnet support.

Today's repo only obtains and distributes modules
via nuget using my scripts for CI/CD;
And for .NET projects also provides related automation.

Someone else can add modules support for relevant platforms via PR;
Then, ... brief search in SO using our packages,
https://stackoverflow.com/a/53654058  etc.
